@startuml "diagramaColaboracion"

skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent
hide members

object ": Actor" as user
object ": Registro" as registro
object ": Catalogo" as catalogo
object ": Venta" as venta
object ": LineaVenta" as linea

user -r-> registro
note on link
    1:introducirArticulo(ArticuloID id, int cant)
end note

registro -r-> catalogo
note on link
    2: espec = catalogo.getEspecificacion(id)
end note

registro -d-> venta
note on link
    3: venta.crearLineaVenta(espec, cant)
end note

venta -r-> linea
note on link
    4:  lineasVenta.añadir(new LineaVenta(espec, cant)
end note

@enduml